services:
  xsushi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xsushi_app
    init: true
    env_file:
      - config/.env
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
